### ISSUE TITLE
[BUG] - Docker Desktop Config folder won't open

### ISSUE THREAD

**Issue by TsinJu** [nwithan8/tauticord#225]
### This bug has not been reported already

- [X] I have verified that this bug has not already been reported.

### You have tried to fix the bug yourself

- [X] I have tried to fix the bug myself.

### Current Behavior

After starting the Docker Container, the config folder won't open/collapse
While trying to open the folder to edit the config, the folder closes immediately

### Expected Behavior

Folder should open

### Steps to Reproduce

From Docker Desktop go to the tauticord container, click on it, go to "Files" and try to open the config folder

**Comment by nwithan8** [comment]
I am unable to replicate this issue using Docker Desktop on MacOS. The file browser remains open for me. The only thing I can think is perhaps the container is restarting itself because the config file is invalid. You should edit the config file from the host machine via the mounted paths, not inside the container.

Awaiting your response, otherwise I will close this task.
