### ISSUE TITLE
[FEATURE] - tauticord.yaml -  UserCount from Performance into Activity

### ISSUE THREAD

**Issue by TsinJu** [nwithan8/tauticord#226]
### This request has not already been submitted

- [X] I have verified that no one has asked for this feature before.

### The feature is appropriate for Tauticord

- [X] I believe this feature is appropriate for Tauticord.

### Feature Type / Category

Other

### Feature Details

UserCount in tauticord.yaml seems to me to be more for Stats: Activity: the right category. 
Had tried to move UserCount to Activity, but with my limited knowledge that led to an error

**Comment by nwithan8** [comment]
At the current moment, I don't intend on changing the category, unless you can convince me otherwise.

My thinking, activity is for what's happening right now, and mirrors all the stats shown on the Tautulli home screen widgets.

User count represents the total number of user accounts, not how many are currently playing something (which is represented by other stats in Activity).

**Comment by TsinJu** [comment]
At least the possibility to vary. There are also others who use the script. Thank you
