### ISSUE TITLE
edit messsage instead of deleate and re send

### ISSUE THREAD

**Issue by TomW1605** [nwithan8/Tauticord#3]
i think it might be better and would have vewer notifications if the bot edited its last message instead of deleating it and sending another. 

i have implamented this and would be happy to make a PR if you want me to.

https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.edit

**Comment by twilsonco** [comment]
Does that keep the latest info at the bottom? I think that’s a nice touch.

**Comment by twilsonco** [comment]
Also, could you please fork with this change?

**Comment by TomW1605** [comment]
@twilsonco i have made a fork with my changes and made a pull request #4. i doubt the pull will be merged but might as well have it in case the author comes back.

**Comment by twilsonco** [comment]
Thanks @TomW1605 !

Just got it up and running. As I mentioned [above](https://github.com/nwithan8/Tauticord/issues/3#issuecomment-608918360), I like that Tauticord is essentially anchored to the bottom of the channel. With this method, however, it can get lost higher in the channel (I keep it on the same channel where Tautulli posts server activity). 

Might I suggest that Tauticord check to see if it's message is the bottom-most in the channel? If so, utilize both of your major features (editing rather than deleting and only posting if the state actually changed). If Tauticord's message _is not_ the bottom most, then on the next refresh it should delete the old message and repost to make it the bottommost, _regardless of whether the state changed_.

Does that make sense?

**Comment by TomW1605** [comment]
right i didnt quite understand what you ment by that as i have a dedicated chanel for active streams so was not an issue. i can't see why your segestion would not work and does not undermine what i have done. i will try and implament it soon.

**Comment by twilsonco** [comment]
Wow @TomW1605 , you’re the best!

No rush though. Assuming the message is never deleted (unless the bot is restarted or something) then pinning it is essentially what I’m after.

**Comment by twilsonco** [comment]
Oh, you already did it! What, are you under lockdown or something? 😷

**Comment by TomW1605** [comment]
no but i sould see how it should be done so it was faster to do now than later

also when you said you had other messages in the chanel i remembered that i was clearing the chanel instead of deleating just the bots last message at startup and i wanted to get that fixed as quickly as posable incase it was a problem

**Comment by TomW1605** [comment]
im going to close this issue now as it is done all bar a PR. any mor issues/requests open a new issue in https://github.com/TomW1605/Tauticord/issues
